package Vista;

import Modelo.Cliente;
import Modelo.ClienteDAO;
import Modelo.DetalleV;
import Modelo.Productos;
import Modelo.ProductosDAO;
import Modelo.Venta;
import Modelo.VentaDAO;
import Modelo.login;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class PrincipalISV extends javax.swing.JFrame {

    ClienteDAO cd = new ClienteDAO();
    Cliente c = new Cliente();
    Productos p = new Productos();
    ProductosDAO pd = new ProductosDAO();
    Venta v = new Venta();
    VentaDAO vd = new VentaDAO();
    DetalleV d = new DetalleV();
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel tb = new DefaultTableModel();
    int item;
    double total = 0.00;

    public PrincipalISV() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtTelefonoV.setVisible(false);
        txtCiudadV.setVisible(false);
        txtidv.setVisible(false);
        lblEmp.setVisible(false);
        pd.BoxCategoria(jComboBoxP);
        cd.BoxTipo(jComboBoxC);
    }

    public void ListaClientes() {
        List<Cliente> ListarCl = cd.Listar();
        model = (DefaultTableModel) TablaClient.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarCl.size(); i++) {
            ob[0] = ListarCl.get(i).getDNI();
            ob[1] = ListarCl.get(i).getNombre();
            ob[2] = ListarCl.get(i).getTelefono();
            ob[3] = ListarCl.get(i).getCiudad();
            ob[4] = ListarCl.get(i).getTipo();
            model.addRow(ob);
        }
        TablaClient.setModel(model);
    }

    public void BorrarTabla() {
        for (int i = 0; i < model.getRowCount(); i++) {
            model.removeRow(i);
            i = i - 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTec = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnNuevaVenta = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnVerVentas = new javax.swing.JButton();
        lblIcon2 = new javax.swing.JLabel();
        lblEmp = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblFondo2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        lblProducto = new javax.swing.JLabel();
        lblCantidad1 = new javax.swing.JLabel();
        txtCantidad1 = new javax.swing.JTextField();
        txtIDProd1 = new javax.swing.JTextField();
        lblIDProd1 = new javax.swing.JLabel();
        txtProducto = new javax.swing.JTextField();
        lblPrecio1 = new javax.swing.JLabel();
        txtPrecio1 = new javax.swing.JTextField();
        lblStock = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaNV = new javax.swing.JTable();
        lblDNI1 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        lblNombreC1 = new javax.swing.JLabel();
        txtNombreC1 = new javax.swing.JTextField();
        btnImprimir1 = new javax.swing.JButton();
        lblTotalaPagar = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnEliminar1 = new javax.swing.JButton();
        lblCategoria1 = new javax.swing.JLabel();
        txtCategoria1 = new javax.swing.JTextField();
        lblTipo1 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        txtTelefonoV = new javax.swing.JTextField();
        txtCiudadV = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lblDNI2 = new javax.swing.JLabel();
        lblNombreC2 = new javax.swing.JLabel();
        txtDNI2 = new javax.swing.JTextField();
        txtNombreC2 = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblCiudad = new javax.swing.JLabel();
        txtCiudad = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaClient = new javax.swing.JTable();
        btnGuardar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar2 = new javax.swing.JButton();
        lblTipo2 = new javax.swing.JLabel();
        jComboBoxC = new javax.swing.JComboBox<>();
        btnRestaurar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblIDProd2 = new javax.swing.JLabel();
        txtIDProd2 = new javax.swing.JTextField();
        lblNombreP = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblPrecio2 = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JTextField();
        lblCantidad2 = new javax.swing.JLabel();
        txtCantidad2 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        btnGuardar2 = new javax.swing.JButton();
        btnActualizar2 = new javax.swing.JButton();
        btnEliminar3 = new javax.swing.JButton();
        lblCategoria2 = new javax.swing.JLabel();
        jComboBoxP = new javax.swing.JComboBox<>();
        btnRestaurar2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaV = new javax.swing.JTable();
        btnImprimir2 = new javax.swing.JButton();
        txtidv = new javax.swing.JTextField();
        btnEliminar4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTec.setBackground(new java.awt.Color(255, 255, 255));
        lblTec.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTec.setForeground(new java.awt.Color(255, 255, 255));
        lblTec.setText("SITEMA DE VENTAS INFOTEC");
        getContentPane().add(lblTec, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 24, 230, 60));

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));
        jPanel2.setForeground(new java.awt.Color(102, 102, 102));

        btnNuevaVenta.setBackground(new java.awt.Color(202, 80, 18));
        btnNuevaVenta.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaVenta.setText("Nueva Venta");
        btnNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaVentaActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(202, 80, 18));
        btnClientes.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnClientes.setForeground(new java.awt.Color(255, 255, 255));
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(202, 80, 18));
        btnProductos.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnVerVentas.setBackground(new java.awt.Color(202, 80, 18));
        btnVerVentas.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 14)); // NOI18N
        btnVerVentas.setForeground(new java.awt.Color(255, 255, 255));
        btnVerVentas.setText("Ver Ventas");
        btnVerVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerVentasActionPerformed(evt);
            }
        });

        lblIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoInfotec.png"))); // NOI18N

        lblEmp.setText("INFOTEC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblIcon2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(lblEmp)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnVerVentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblIcon2)
                .addGap(18, 18, 18)
                .addComponent(lblEmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevaVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVerVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        jPanel8.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 190, 130));

        lblFondo2.setBackground(new java.awt.Color(51, 51, 51));
        lblFondo2.setForeground(new java.awt.Color(51, 51, 51));
        lblFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo2.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(lblFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblFondo2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 610, 130));

        jPanel4.setBackground(new java.awt.Color(204, 102, 0));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        lblProducto.setBackground(new java.awt.Color(255, 255, 255));
        lblProducto.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblProducto.setText("Producto");

        lblCantidad1.setBackground(new java.awt.Color(255, 255, 255));
        lblCantidad1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad1.setText("Cantidad");

        txtCantidad1.setBackground(new java.awt.Color(204, 102, 0));
        txtCantidad1.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCantidad1.setBorder(null);
        txtCantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad1ActionPerformed(evt);
            }
        });
        txtCantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCantidad1KeyPressed(evt);
            }
        });

        txtIDProd1.setBackground(new java.awt.Color(202, 102, 0));
        txtIDProd1.setForeground(new java.awt.Color(255, 255, 255));
        txtIDProd1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtIDProd1.setBorder(null);
        txtIDProd1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDProd1KeyPressed(evt);
            }
        });

        lblIDProd1.setBackground(new java.awt.Color(255, 255, 255));
        lblIDProd1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblIDProd1.setForeground(new java.awt.Color(255, 255, 255));
        lblIDProd1.setText("ID");

        txtProducto.setBackground(new java.awt.Color(202, 102, 0));
        txtProducto.setForeground(new java.awt.Color(255, 255, 255));
        txtProducto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtProducto.setBorder(null);

        lblPrecio1.setBackground(new java.awt.Color(255, 255, 255));
        lblPrecio1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio1.setText("Precio");

        txtPrecio1.setBackground(new java.awt.Color(204, 102, 0));
        txtPrecio1.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPrecio1.setBorder(null);

        lblStock.setBackground(new java.awt.Color(255, 255, 255));
        lblStock.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblStock.setForeground(new java.awt.Color(255, 255, 255));
        lblStock.setText("Stock");

        txtStock.setEditable(false);
        txtStock.setBackground(new java.awt.Color(204, 102, 0));
        txtStock.setForeground(new java.awt.Color(255, 255, 255));
        txtStock.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtStock.setBorder(null);

        TablaNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CODIGO", "PRODUCTO", "CATEGORIA", "CANTIDAD", "PRECIO", "TOTAL"
            }
        ));
        jScrollPane1.setViewportView(TablaNV);
        if (TablaNV.getColumnModel().getColumnCount() > 0) {
            TablaNV.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaNV.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaNV.getColumnModel().getColumn(2).setPreferredWidth(50);
            TablaNV.getColumnModel().getColumn(3).setPreferredWidth(30);
            TablaNV.getColumnModel().getColumn(4).setPreferredWidth(30);
            TablaNV.getColumnModel().getColumn(5).setResizable(false);
            TablaNV.getColumnModel().getColumn(5).setPreferredWidth(40);
        }

        lblDNI1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblDNI1.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI1.setText("DNI");

        txtDNI.setBackground(new java.awt.Color(204, 102, 0));
        txtDNI.setForeground(new java.awt.Color(255, 255, 255));
        txtDNI.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDNI.setBorder(null);
        txtDNI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtDNIKeyPressed(evt);
            }
        });

        lblNombreC1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblNombreC1.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreC1.setText("Nombre");

        txtNombreC1.setBackground(new java.awt.Color(204, 102, 0));
        txtNombreC1.setForeground(new java.awt.Color(255, 255, 255));
        txtNombreC1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNombreC1.setBorder(null);

        btnImprimir1.setBackground(new java.awt.Color(115, 139, 28));
        btnImprimir1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnImprimir1.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir1.setText("REGISTRAR");
        btnImprimir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        lblTotalaPagar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblTotalaPagar.setForeground(new java.awt.Color(255, 255, 255));
        lblTotalaPagar.setText("TOTAL A PAGAR");

        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("_______");

        btnEliminar1.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnEliminar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setText("ELIMINAR");
        btnEliminar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });

        lblCategoria1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria1.setText("Categoria");

        txtCategoria1.setBackground(new java.awt.Color(202, 102, 0));
        txtCategoria1.setForeground(new java.awt.Color(255, 255, 255));
        txtCategoria1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtCategoria1.setBorder(null);

        lblTipo1.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        lblTipo1.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo1.setText("Tipo");

        txtTipo.setBackground(new java.awt.Color(204, 102, 0));
        txtTipo.setForeground(new java.awt.Color(255, 255, 255));
        txtTipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTipo.setBorder(null);

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnImprimir1)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar1))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(jSeparator2)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(lblIDProd1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator3))
                    .addComponent(lblCantidad1))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(lblPrecio1)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblCategoria1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator5)
                            .addComponent(txtCategoria1, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblStock)))
                .addGap(42, 42, 42))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblDNI1)
                .addGap(135, 135, 135)
                .addComponent(lblNombreC1)
                .addGap(120, 120, 120)
                .addComponent(lblTipo1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 739, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreC1, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(jSeparator7))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTipo, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(jSeparator9))
                        .addGap(32, 32, 32)
                        .addComponent(txtTelefonoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCiudadV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalaPagar)
                        .addGap(28, 28, 28)
                        .addComponent(lblTotal)
                        .addGap(80, 80, 80))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(lblCantidad1)
                    .addComponent(lblIDProd1)
                    .addComponent(lblPrecio1)
                    .addComponent(lblStock)
                    .addComponent(lblCategoria1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtIDProd1)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCategoria1)
                            .addComponent(txtPrecio1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir1)
                    .addComponent(btnEliminar1))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI1)
                    .addComponent(lblNombreC1)
                    .addComponent(lblTipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDNI)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalaPagar)
                        .addComponent(lblTotal)
                        .addComponent(txtTelefonoV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCiudadV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombreC1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel1.setBackground(new java.awt.Color(204, 102, 0));

        lblDNI2.setForeground(new java.awt.Color(255, 255, 255));
        lblDNI2.setText("DNI");

        lblNombreC2.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreC2.setText("Nombre");

        txtDNI2.setBackground(new java.awt.Color(154, 83, 6));
        txtDNI2.setForeground(new java.awt.Color(255, 255, 255));
        txtDNI2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNI2ActionPerformed(evt);
            }
        });

        txtNombreC2.setBackground(new java.awt.Color(154, 83, 6));
        txtNombreC2.setForeground(new java.awt.Color(255, 255, 255));

        lblTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lblTelefono.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefono.setText("Telefono");

        txtTelefono.setBackground(new java.awt.Color(154, 83, 6));
        txtTelefono.setForeground(new java.awt.Color(255, 255, 255));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });

        lblCiudad.setForeground(new java.awt.Color(255, 255, 255));
        lblCiudad.setText("Ciudad");

        txtCiudad.setBackground(new java.awt.Color(154, 83, 6));
        txtCiudad.setForeground(new java.awt.Color(255, 255, 255));

        TablaClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "NOMBRE", "TELEFONO", "CIUDAD", "TIPO"
            }
        ));
        TablaClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaClient);
        if (TablaClient.getColumnModel().getColumnCount() > 0) {
            TablaClient.getColumnModel().getColumn(0).setPreferredWidth(50);
            TablaClient.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaClient.getColumnModel().getColumn(2).setPreferredWidth(50);
            TablaClient.getColumnModel().getColumn(3).setPreferredWidth(50);
            TablaClient.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        btnGuardar1.setBackground(new java.awt.Color(0, 0, 102));
        btnGuardar1.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("GUARDAR");
        btnGuardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnActualizar1.setBackground(new java.awt.Color(0, 102, 0));
        btnActualizar1.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar1.setText("ACTUALIZAR");
        btnActualizar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        btnEliminar2.setBackground(new java.awt.Color(204, 51, 0));
        btnEliminar2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnEliminar2.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar2.setText("ELIMINAR");
        btnEliminar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar2ActionPerformed(evt);
            }
        });

        lblTipo2.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo2.setText("Tipo");

        jComboBoxC.setBackground(new java.awt.Color(154, 83, 6));
        jComboBoxC.setForeground(new java.awt.Color(154, 83, 6));

        btnRestaurar1.setBackground(new java.awt.Color(102, 102, 0));
        btnRestaurar1.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnRestaurar1.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurar1.setText("RESTAURAR");
        btnRestaurar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombreC2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jComboBoxC, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(btnActualizar1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardar1)
                .addGap(82, 82, 82)
                .addComponent(btnEliminar2)
                .addGap(84, 84, 84)
                .addComponent(btnRestaurar1)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblDNI2)
                .addGap(129, 129, 129)
                .addComponent(lblNombreC2)
                .addGap(125, 125, 125)
                .addComponent(lblTelefono)
                .addGap(104, 104, 104)
                .addComponent(lblCiudad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTipo2)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDNI2)
                    .addComponent(lblNombreC2)
                    .addComponent(lblTelefono)
                    .addComponent(lblCiudad)
                    .addComponent(lblTipo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDNI2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombreC2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar1)
                    .addComponent(btnEliminar2)
                    .addComponent(btnGuardar1)
                    .addComponent(btnRestaurar1))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel1);

        jPanel3.setBackground(new java.awt.Color(204, 102, 0));

        lblIDProd2.setForeground(new java.awt.Color(255, 255, 255));
        lblIDProd2.setText("ID");

        txtIDProd2.setBackground(new java.awt.Color(154, 83, 6));
        txtIDProd2.setForeground(new java.awt.Color(255, 255, 255));
        txtIDProd2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDProd2KeyPressed(evt);
            }
        });

        lblNombreP.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreP.setText("Nombre");

        txtNombreP.setBackground(new java.awt.Color(154, 83, 6));
        txtNombreP.setForeground(new java.awt.Color(255, 255, 255));

        lblPrecio2.setForeground(new java.awt.Color(255, 255, 255));
        lblPrecio2.setText("Precio");

        txtPrecio2.setBackground(new java.awt.Color(154, 83, 6));
        txtPrecio2.setForeground(new java.awt.Color(255, 255, 255));
        txtPrecio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecio2ActionPerformed(evt);
            }
        });

        lblCantidad2.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidad2.setText("Cantidad");

        txtCantidad2.setBackground(new java.awt.Color(154, 83, 6));
        txtCantidad2.setForeground(new java.awt.Color(255, 255, 255));
        txtCantidad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidad2ActionPerformed(evt);
            }
        });

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "CATEGORIA", "STOCK", "PRECIO"
            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(TablaProductos);
        if (TablaProductos.getColumnModel().getColumnCount() > 0) {
            TablaProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            TablaProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaProductos.getColumnModel().getColumn(2).setPreferredWidth(50);
            TablaProductos.getColumnModel().getColumn(3).setPreferredWidth(50);
            TablaProductos.getColumnModel().getColumn(4).setPreferredWidth(50);
        }

        btnGuardar2.setBackground(new java.awt.Color(0, 0, 102));
        btnGuardar2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnGuardar2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar2.setText("GUARDAR");
        btnGuardar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar2ActionPerformed(evt);
            }
        });

        btnActualizar2.setBackground(new java.awt.Color(0, 102, 0));
        btnActualizar2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnActualizar2.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar2.setText("ACTUALIZAR");
        btnActualizar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnActualizar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar2ActionPerformed(evt);
            }
        });

        btnEliminar3.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar3.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnEliminar3.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar3.setText("ELIMINAR");
        btnEliminar3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar3ActionPerformed(evt);
            }
        });

        lblCategoria2.setBackground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoria2.setText("Categoria");

        jComboBoxP.setBackground(new java.awt.Color(154, 83, 6));

        btnRestaurar2.setBackground(new java.awt.Color(102, 102, 0));
        btnRestaurar2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnRestaurar2.setForeground(new java.awt.Color(255, 255, 255));
        btnRestaurar2.setText("RESTAURAR");
        btnRestaurar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestaurar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnGuardar2)
                            .addComponent(btnEliminar3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnActualizar2)
                            .addComponent(btnRestaurar2)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCategoria2)
                            .addComponent(lblCantidad2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxP, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreP)
                            .addComponent(lblIDProd2)
                            .addComponent(lblPrecio2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(txtIDProd2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIDProd2)
                            .addComponent(txtIDProd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombreP)
                            .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecio2)
                            .addComponent(txtPrecio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantidad2)
                            .addComponent(txtCantidad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCategoria2)
                            .addComponent(jComboBoxP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(btnGuardar2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar3)
                            .addComponent(btnRestaurar2))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab3", jPanel3);

        jPanel6.setBackground(new java.awt.Color(204, 102, 0));

        TablaV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "COD", "CLIENTE", "VENDEDOR", "TOTAL"
            }
        ));
        TablaV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TablaV);
        if (TablaV.getColumnModel().getColumnCount() > 0) {
            TablaV.getColumnModel().getColumn(0).setPreferredWidth(50);
            TablaV.getColumnModel().getColumn(1).setPreferredWidth(100);
            TablaV.getColumnModel().getColumn(2).setPreferredWidth(100);
            TablaV.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        btnImprimir2.setBackground(new java.awt.Color(0, 102, 102));
        btnImprimir2.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnImprimir2.setForeground(new java.awt.Color(255, 255, 255));
        btnImprimir2.setText("IMPRIMIR");
        btnImprimir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImprimir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir2ActionPerformed(evt);
            }
        });

        btnEliminar4.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminar4.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btnEliminar4.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar4.setText("ELIMINAR");
        btnEliminar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(btnImprimir2)
                        .addGap(130, 130, 130)
                        .addComponent(btnEliminar4))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(txtidv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtidv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir2)
                    .addComponent(btnEliminar4))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 800, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed

        if (txtDNI2.getText().isEmpty() || txtNombreC2.getText().isEmpty() || txtTelefono.getText().isEmpty() || txtCiudad.getText().isEmpty() || jComboBoxC.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.");
            return;
        }

        String dniText = txtDNI2.getText();

        dniText = dniText.trim().replaceAll("[^0-9]", "");

        if (!dniText.matches("[0-9]+") || dniText.length() != 8) {
            JOptionPane.showMessageDialog(null, "El DNI debe contener exactamente 8 números válidos.");
            return;
        }

        String telefonoText = txtTelefono.getText();
        telefonoText = telefonoText.trim().replaceAll("[^0-9]", "");
        if (!telefonoText.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El teléfono debe contener solo números.");
            return;
        }

        c.setDNI(Integer.parseInt(dniText));
        c.setNombre(txtNombreC2.getText());
        c.setTelefono(Integer.parseInt(telefonoText));
        c.setCiudad(txtCiudad.getText());
        c.setTipo(jComboBoxC.getSelectedItem().toString());
        cd.RegistroClient(c);
        BorrarTabla();
        LimpiarCasillasC();
        ListaClientes();
        JOptionPane.showMessageDialog(null, "Cliente Guardado");
    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // TODO add your handling code here:
        BorrarTabla();
        ListaClientes();
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void TablaClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaClientMouseClicked
        // TODO add your handling code here:
        int f = TablaClient.rowAtPoint(evt.getPoint());
        txtDNI2.setText(TablaClient.getValueAt(f, 0).toString());
        txtNombreC2.setText(TablaClient.getValueAt(f, 1).toString());
        txtTelefono.setText(TablaClient.getValueAt(f, 2).toString());
        txtCiudad.setText(TablaClient.getValueAt(f, 3).toString());
        jComboBoxC.setSelectedItem(TablaClient.getValueAt(f, 4).toString());

    }//GEN-LAST:event_TablaClientMouseClicked

    private void btnEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar2ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtDNI2.getText())) {
            int pg = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar?");
            if (pg == 0) {
                int DNI = Integer.parseInt(txtDNI2.getText());
                cd.EliminarC(DNI);
                BorrarTabla();
                LimpiarCasillasC();
                ListaClientes();
            }
        }
    }//GEN-LAST:event_btnEliminar2ActionPerformed


    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtDNI2.getText())) {
            JOptionPane.showMessageDialog(null, "Escoga una fila");
        } else {
            c.setNombre(txtNombreC2.getText());
            c.setTelefono(Integer.parseInt(txtTelefono.getText()));
            c.setCiudad(txtCiudad.getText());
            c.setTipo(jComboBoxC.getSelectedItem().toString());
            c.setDNI(Integer.parseInt(txtDNI2.getText()));
            if (!"".equals(txtNombreC2.getText()) || !"".equals(txtTelefono.getText()) || !"".equals(txtCiudad.getText())) {
                cd.ActualizarC(c);
                BorrarTabla();
                LimpiarCasillasC();
                ListaClientes();
            }
        }
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnGuardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar2ActionPerformed
        // TODO add your handling code here:
        if (txtIDProd2.getText().isEmpty() || txtNombreP.getText().isEmpty() || jComboBoxP.getSelectedItem() == null || txtCantidad2.getText().isEmpty() || txtPrecio2.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, completa todos los campos.");
            return; 
        }

        String precioText = txtPrecio2.getText();
        precioText = precioText.trim().replaceAll("[^0-9]", "");
        if (!precioText.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "El precio debe contener solo números.");
            return; 
        }
    
        String cantidadText = txtCantidad2.getText();
        cantidadText = cantidadText.trim().replaceAll("[^0-9]", "");
        if (!cantidadText.matches("[0-9]+")) {
            JOptionPane.showMessageDialog(null, "La cantidad debe contener solo números.");
            return; 
        }

        p.setId_producto(Integer.parseInt(txtIDProd2.getText()));
        p.setNombre_prod(txtNombreP.getText());
        p.setCategoria(jComboBoxP.getSelectedItem().toString());
        p.setStock(Integer.parseInt(cantidadText));
        p.setPrecio(Double.parseDouble(precioText));
        pd.RegistroProd(p);
        BorrarTabla();
        LimpiarCasillasP();
        ListaProductos();
        JOptionPane.showMessageDialog(null, "Producto Guardado");
    }//GEN-LAST:event_btnGuardar2ActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // TODO add your handling code here:
        BorrarTabla();
        ListaProductos();
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnEliminar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar3ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtIDProd2.getText())) {
            int pg = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar?");
            if (pg == 0) {
                int id_producto = Integer.parseInt(txtIDProd2.getText());
                pd.EliminarP(id_producto);
                BorrarTabla();
                LimpiarCasillasP();
                ListaProductos();
            }
        }
    }//GEN-LAST:event_btnEliminar3ActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
        // TODO add your handling code here:
        int f = TablaProductos.rowAtPoint(evt.getPoint());
        txtIDProd2.setText(TablaProductos.getValueAt(f, 0).toString());
        txtNombreP.setText(TablaProductos.getValueAt(f, 1).toString());
        jComboBoxP.setSelectedItem(TablaProductos.getValueAt(f, 2).toString());
        txtCantidad2.setText(TablaProductos.getValueAt(f, 3).toString());
        txtPrecio2.setText(TablaProductos.getValueAt(f, 4).toString());
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void btnActualizar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar2ActionPerformed
        // TODO add your handling code here:
        if ("".equals(txtIDProd2.getText())) {
            JOptionPane.showMessageDialog(null, "Escoga una fila");
        } else {
            p.setNombre_prod(txtNombreP.getText());
            p.setCategoria(jComboBoxP.getSelectedItem().toString());
            p.setStock(Integer.parseInt(txtCantidad2.getText()));
            p.setPrecio(Double.parseDouble(txtPrecio2.getText()));
            p.setId_producto(Integer.parseInt(txtIDProd2.getText()));
            if (!"".equals(txtNombreP.getText()) || !"".equals(txtCantidad2.getText()) || !"".equals(txtPrecio2.getText())) {
                pd.ActualizarP(p);
                BorrarTabla();
                LimpiarCasillasP();
                ListaProductos();
            }
        }
    }//GEN-LAST:event_btnActualizar2ActionPerformed

    private void txtIDProd2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDProd2KeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIDProd2KeyPressed

    private void btnNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaVentaActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btnNuevaVentaActionPerformed

    private void btnVerVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerVentasActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        BorrarTabla();
        ListaVentas();
    }//GEN-LAST:event_btnVerVentasActionPerformed

    private void TablaVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVMouseClicked
        // TODO add your handling code here:
        int f = TablaV.rowAtPoint(evt.getPoint());
        txtidv.setText(TablaV.getValueAt(f, 0).toString());
    }//GEN-LAST:event_TablaVMouseClicked

    private void btnImprimir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir2ActionPerformed
        // TODO add your handling code here:
        try {
            int id = Integer.parseInt(txtidv.getText());
            File ar = new File("src/pdf/dventa" + id + ".pdf");
            Desktop.getDesktop().open(ar);
        } catch (IOException ex) {
            Logger.getLogger(PrincipalISV.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnImprimir2ActionPerformed

    private void btnEliminar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar4ActionPerformed
        // TODO add your handling code here:
        if (!"".equals(txtidv.getText())) {
            int pg = JOptionPane.showConfirmDialog(null, "Estas seguro de eliminar?");
            if (pg == 0) {
                int id_venta = Integer.parseInt(txtidv.getText());
                vd.EliminarV(id_venta);
                BorrarTabla();
                ListaVentas();
            }
        }
    }//GEN-LAST:event_btnEliminar4ActionPerformed

    private void btnRestaurar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurar1ActionPerformed
        // TODO add your handling code here:
        LimpiarCasillasC();
    }//GEN-LAST:event_btnRestaurar1ActionPerformed

    private void btnRestaurar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurar2ActionPerformed
        // TODO add your handling code here:
        LimpiarCasillasP();
    }//GEN-LAST:event_btnRestaurar2ActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        model = (DefaultTableModel) TablaNV.getModel();
        model.removeRow(TablaNV.getSelectedRow());
        TotalV();
        txtIDProd1.requestFocus();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        // TODO add your handling code here:
        RegistrarV();
        RegistrarD();
        AStock();
        pdf();
        BorrarTablaV();
        LimpiarCasillasCN();
        JOptionPane.showMessageDialog(this, "Venta registrada");
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    private void txtDNIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDNIKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtDNI.getText())) {
                int DNI = Integer.parseInt(txtDNI.getText());
                c = cd.BuscarC(DNI);
                if (c.getNombre() != null) {
                    txtNombreC1.setText("" + c.getNombre());
                    txtTipo.setText("" + c.getTipo());
                    txtTelefonoV.setText("" + c.getTelefono());
                    txtCiudadV.setText("" + c.getCiudad());
                } else {
                    txtDNI.setText("");
                    JOptionPane.showMessageDialog(null, "Cliente Inexistente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingresa el DNI del cliente");
                txtDNI.requestFocus();
            }
        }
    }//GEN-LAST:event_txtDNIKeyPressed

    private void txtIDProd1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDProd1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtIDProd1.getText())) {
                int id_producto = Integer.parseInt(txtIDProd1.getText());
                p = pd.BuscarP(id_producto);
                if (p.getNombre_prod() != null) {
                    txtProducto.setText("" + p.getNombre_prod());
                    txtPrecio1.setText("" + p.getPrecio());
                    txtCategoria1.setText("" + p.getCategoria());
                    txtStock.setText("" + p.getStock());
                    txtCantidad1.requestFocus();
                } else {
                    txtProducto.setText("");
                    txtPrecio1.setText("");
                    txtCategoria1.setText("");
                    txtStock.setText("");
                    txtIDProd1.requestFocus();
                    JOptionPane.showMessageDialog(null, "Producto inexistente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingresa el codigo del producto");
                txtIDProd1.requestFocus();
            }
        }
    }//GEN-LAST:event_txtIDProd1KeyPressed

    private void txtCantidad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidad1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!"".equals(txtCantidad1.getText())) {
                String id = txtIDProd1.getText();
                String producto = txtProducto.getText();
                String categoria = txtCategoria1.getText();
                int cant = Integer.parseInt(txtCantidad1.getText());
                double precio = Double.parseDouble(txtPrecio1.getText());
                double total = cant * precio;
                int stock = Integer.parseInt(txtStock.getText());
                if (stock >= cant) {
                    item = item + 1;
                    DefaultTableModel tb = (DefaultTableModel) TablaNV.getModel();
                    ArrayList listV = new ArrayList();
                    listV.add(item);
                    listV.add(id);
                    listV.add(producto);
                    listV.add(categoria);
                    listV.add(cant);
                    listV.add(precio);
                    listV.add(total);
                    Object[] ob = new Object[6];
                    ob[0] = listV.get(1);
                    ob[1] = listV.get(2);
                    ob[2] = listV.get(3);
                    ob[3] = listV.get(4);
                    ob[4] = listV.get(5);
                    ob[5] = listV.get(6);
                    tb.addRow(ob);
                    TablaNV.setModel(tb);
                    TotalV();
                    LimpiarCasillasV();
                    txtIDProd1.requestFocus();
                } else {
                    JOptionPane.showMessageDialog(null, "Stock insuficiente");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingresar cantidad");
            }
        }
    }//GEN-LAST:event_txtCantidad1KeyPressed

    private void txtCantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad1ActionPerformed

    private void txtDNI2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNI2ActionPerformed
        // TODO add your handling code here:      
    }//GEN-LAST:event_txtDNI2ActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtCantidad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidad2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidad2ActionPerformed

    private void txtPrecio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecio2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecio2ActionPerformed

    private void TotalV() {
        total = 0.00;
        int f = TablaNV.getRowCount();
        for (int i = 0; i < f; i++) {
            double t = Double.parseDouble(String.valueOf(TablaNV.getModel().getValueAt(i, 5)));
            total = total + t;
        }
        lblTotal.setText(String.format("%.2f", total));
    }

    public void ListaProductos() {
        List<Productos> ListarP = pd.Listar();
        model = (DefaultTableModel) TablaProductos.getModel();
        Object[] ob = new Object[5];
        for (int i = 0; i < ListarP.size(); i++) {
            ob[0] = ListarP.get(i).getId_producto();
            ob[1] = ListarP.get(i).getNombre_prod();
            ob[2] = ListarP.get(i).getCategoria();
            ob[3] = ListarP.get(i).getStock();
            ob[4] = ListarP.get(i).getPrecio();
            model.addRow(ob);
        }
        TablaProductos.setModel(model);
    }

    public void ListaVentas() {
        List<Venta> ListarV = vd.Listar();
        model = (DefaultTableModel) TablaV.getModel();
        Object[] ob = new Object[4];
        for (int i = 0; i < ListarV.size(); i++) {
            ob[0] = ListarV.get(i).getIdVenta();
            ob[1] = ListarV.get(i).getDniV();
            ob[2] = ListarV.get(i).getVend();
            ob[3] = ListarV.get(i).getTotal();
            model.addRow(ob);
        }
        TablaV.setModel(model);
    }

    private void LimpiarCasillasV() {
        txtIDProd1.setText("");
        txtProducto.setText("");
        txtCantidad1.setText("");
        txtPrecio1.setText("");
        txtCategoria1.setText("");
        txtStock.setText("");

    }

    private void LimpiarCasillasC() {
        txtDNI2.setText("");
        txtNombreC2.setText("");
        txtTelefono.setText("");
        txtCiudad.setText("");
    }

    private void LimpiarCasillasP() {
        txtIDProd2.setText("");
        txtNombreP.setText("");
        txtPrecio2.setText("");
        txtCantidad2.setText("");
    }

    private void LimpiarCasillasCN() {
        txtDNI.setText("");
        txtNombreC1.setText("");
        txtTipo.setText("");
        txtTelefonoV.setText("");
        txtCiudadV.setText("");
    }

    private void RegistrarV() {
        int dni = Integer.parseInt(txtDNI.getText());
        String Vend = lblEmp.getText();
        double totalV = total;
        v.setDniV(dni);
        v.setVend(Vend);
        v.setTotal(totalV);
        vd.RegistrarV(v);

    }

    public void RegistrarD() {
        int idV = vd.IDV();
        for (int i = 0; i < TablaNV.getRowCount(); i++) {
            int idP = Integer.parseInt(TablaNV.getValueAt(i, 0).toString());
            int cant = Integer.parseInt(TablaNV.getValueAt(i, 3).toString());
            double prec = Double.parseDouble(TablaNV.getValueAt(i, 4).toString());
            d.setIdP(idP);
            d.setCant(cant);
            d.setPrec(prec);
            d.setIdV(idV);
            vd.RegistrarD(d);
        }
    }

    private void AStock() {
        for (int i = 0; i < TablaNV.getRowCount(); i++) {
            int idP = Integer.parseInt(TablaNV.getValueAt(i, 0).toString());
            int cant = Integer.parseInt(TablaNV.getValueAt(i, 3).toString());
            p = pd.BuscarP(idP);
            int stockA = p.getStock() - cant;
            vd.AStock(stockA, idP);
        }
    }

    private void BorrarTablaV() {
        tb = (DefaultTableModel) TablaNV.getModel();
        int f = TablaNV.getRowCount();
        for (int i = 0; i < f; i++) {
            tb.removeRow(0);
        }
    }

    private void pdf() {
        try {
            FileOutputStream archivo;
            int id = vd.IDV();
            File ar = new File("src/pdf/dventa" + id + ".pdf");
            archivo = new FileOutputStream(ar);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image img = Image.getInstance("src/Img/logoInfotec.png");
            Paragraph fec = new Paragraph();
            Font w = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD, BaseColor.BLACK);
            fec.add(Chunk.NEWLINE);
            Date dat = new Date();
            fec.add("Factura: " + id + "\n" + "Fecha: " + new SimpleDateFormat("dd-MM-yyyy").format(dat) + "\n\n");

            PdfPTable Encabezado = new PdfPTable(4);
            Encabezado.setWidthPercentage(100);
            Encabezado.getDefaultCell().setBorder(0);
            float[] ColumnaEncabezado = new float[]{20f, 30f, 70f, 40f};
            Encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            Encabezado.addCell(img);

            String ruc = "10481712854";
            String nombre = "INFOTEC";
            String telf = "987345201";
            String direc = "Lima-Comas";
            Encabezado.addCell("");
            Encabezado.addCell("RUC: " + ruc + "\nNOMBRE: " + nombre + "\nTELEFONO: " + telf + "\nDIRECCION: " + direc);
            Encabezado.addCell(fec);
            doc.add(Encabezado);

            Paragraph c = new Paragraph();
            c.add(Chunk.NEWLINE);
            Font boldFont = new Font(Font.FontFamily.HELVETICA, 14, Font.BOLD);
            Chunk datosCliente = new Chunk("DATOS DEL CLIENTE", boldFont);
            c.add(datosCliente);
            c.add(Chunk.NEWLINE);
            c.add(Chunk.NEWLINE);
            doc.add(c);
            PdfPTable Tc = new PdfPTable(4);
            Tc.setWidthPercentage(100);
            Tc.getDefaultCell().setBorder(0);
            float[] ColumnaC = new float[]{20f, 50f, 30f, 40f};
            Tc.setWidths(ColumnaC);
            Tc.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell c1 = new PdfPCell(new Phrase("DNI", w));
            PdfPCell c2 = new PdfPCell(new Phrase("NOMBRE", w));
            PdfPCell c3 = new PdfPCell(new Phrase("TELEFONO", w));
            PdfPCell c4 = new PdfPCell(new Phrase("CIUDAD", w));
            c1.setBorder(0);
            c2.setBorder(0);
            c3.setBorder(0);
            c4.setBorder(0);
            c1.setBackgroundColor(BaseColor.ORANGE);
            c2.setBackgroundColor(BaseColor.ORANGE);
            c3.setBackgroundColor(BaseColor.ORANGE);
            c4.setBackgroundColor(BaseColor.ORANGE);
            Tc.addCell(c1);
            Tc.addCell(c2);
            Tc.addCell(c3);
            Tc.addCell(c4);
            Tc.addCell(txtDNI.getText());
            Tc.addCell(txtNombreC1.getText());
            Tc.addCell(txtTelefonoV.getText());
            Tc.addCell(txtCiudadV.getText());
            doc.add(Tc);

            PdfPTable Tp = new PdfPTable(4);
            Tp.setWidthPercentage(100);
            Tp.getDefaultCell().setBorder(0);
            float[] ColumnaP = new float[]{10f, 40f, 20f, 30f};
            Tp.setWidths(ColumnaP);
            Tp.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell p1 = new PdfPCell(new Phrase("CANT", w));
            PdfPCell p2 = new PdfPCell(new Phrase("DESCRIPCION", w));
            PdfPCell p3 = new PdfPCell(new Phrase("PRECIO", w));
            PdfPCell p4 = new PdfPCell(new Phrase("TOTAL", w));
            p1.setBorder(0);
            p2.setBorder(0);
            p3.setBorder(0);
            p4.setBorder(0);
            p1.setBackgroundColor(BaseColor.ORANGE);
            p2.setBackgroundColor(BaseColor.ORANGE);
            p3.setBackgroundColor(BaseColor.ORANGE);
            p4.setBackgroundColor(BaseColor.ORANGE);
            Tp.addCell(p1);
            Tp.addCell(p2);
            Tp.addCell(p3);
            Tp.addCell(p4);
            for (int i = 0; i < TablaNV.getRowCount(); i++) {
                String prod = TablaNV.getValueAt(i, 1).toString();
                String cant = TablaNV.getValueAt(i, 3).toString();
                String pre = TablaNV.getValueAt(i, 4).toString();
                String tot = TablaNV.getValueAt(i, 5).toString();
                Tp.addCell(cant);
                Tp.addCell(prod);
                Tp.addCell(pre);
                Tp.addCell(tot);
            }
            doc.add(Tp);

            Paragraph inf = new Paragraph();
            inf.add(Chunk.NEWLINE);
            inf.add("Total " + total);
            inf.setAlignment(Element.ALIGN_RIGHT);
            doc.add(inf);

            Paragraph msg = new Paragraph();
            msg.add(Chunk.NEWLINE);
            msg.add("GRACIAS POR SU COMPRA");
            msg.setAlignment(Element.ALIGN_CENTER);
            doc.add(msg);

            doc.close();
            archivo.close();

        } catch (Exception e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalISV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalISV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalISV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalISV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalISV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaClient;
    private javax.swing.JTable TablaNV;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JTable TablaV;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnActualizar2;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnEliminar2;
    private javax.swing.JButton btnEliminar3;
    private javax.swing.JButton btnEliminar4;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnGuardar2;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JButton btnNuevaVenta;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnRestaurar1;
    private javax.swing.JButton btnRestaurar2;
    private javax.swing.JButton btnVerVentas;
    private javax.swing.JComboBox<String> jComboBoxC;
    private javax.swing.JComboBox<String> jComboBoxP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCantidad1;
    private javax.swing.JLabel lblCantidad2;
    private javax.swing.JLabel lblCategoria1;
    private javax.swing.JLabel lblCategoria2;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblDNI1;
    private javax.swing.JLabel lblDNI2;
    private javax.swing.JLabel lblEmp;
    private javax.swing.JLabel lblFondo2;
    private javax.swing.JLabel lblIDProd1;
    private javax.swing.JLabel lblIDProd2;
    private javax.swing.JLabel lblIcon2;
    private javax.swing.JLabel lblNombreC1;
    private javax.swing.JLabel lblNombreC2;
    private javax.swing.JLabel lblNombreP;
    private javax.swing.JLabel lblPrecio1;
    private javax.swing.JLabel lblPrecio2;
    private javax.swing.JLabel lblProducto;
    private javax.swing.JLabel lblStock;
    private javax.swing.JLabel lblTec;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipo1;
    private javax.swing.JLabel lblTipo2;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalaPagar;
    private javax.swing.JTextField txtCantidad1;
    private javax.swing.JTextField txtCantidad2;
    private javax.swing.JTextField txtCategoria1;
    private javax.swing.JTextField txtCiudad;
    private javax.swing.JTextField txtCiudadV;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtDNI2;
    private javax.swing.JTextField txtIDProd1;
    private javax.swing.JTextField txtIDProd2;
    private javax.swing.JTextField txtNombreC1;
    private javax.swing.JTextField txtNombreC2;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtPrecio1;
    private javax.swing.JTextField txtPrecio2;
    private javax.swing.JTextField txtProducto;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefonoV;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtidv;
    // End of variables declaration//GEN-END:variables
}
